apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: poctest
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/Waheena411/argocdtest'
    targetRevision: 'main'
    path: 'poc'
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
