apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  namespace: poc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
      annotations:
        container.apparmor.security.beta.kubernetes.io/web: runtime/default
    spec:
      automountServiceAccountToken: false 
      nodeSelector:
        agentpool: appuat
      securityContext:
        fsGroup: 2000
        runAsGroup: 2000
        runAsUser: 1000        
        #readOnlyRootFilesystem: true
      containers:
        - name: web
          image: intuitionsaasprod.azurecr.io/linux/intuition/web:2023.114.18714-05db89795c
          command: ["dotnet"]
          args: ["Intuition.Web.dll"]
          resources:
            requests:
              cpu: "100m"
              memory: "200Mi"
            limits:
              cpu: "300m"
              memory: "300Mi"
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            periodSeconds: 5
            timeoutSeconds: 60
          securityContext:
            runAsUser: 1000 
            allowPrivilegeEscalation: false
            capabilities:
              drop: ["ALL"]
              add: ["NET_BIND_SERVICE", "SYS_TIME"]            
          env:
            - name: WebUrl
              value: "https://cstest.intuitioncloud.io"
            - name: ApiUrl
              value: "https://cstest.api.intuitioncloud.io/api/v1"
            - name: Auth__Authority
              value: "https://cstest.auth.intuitioncloud.io"
            - name: Logging__LogLevel__Default
              value: "Warning"
            - name: Logging__Console__LogLevel
              value: "Warning"              
          #- name: Dashboard__Embed=1a2f64e0-9d57-11e9-8400-9bd68a15f197?embed
          #  value: "true"
          #- name: Dashboard__Technical=daeac560-9d59-11e9-8400-9bd68a15f197?embed
          #  value: "true"
---
apiVersion: v1
kind: Service
metadata:
  name: web
  namespace: poc
spec:
  type: ClusterIP
  selector:
    app: web
  ports:
    - port: 80
      targetPort: 8080
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: web
  namespace: poc
spec:
  minAvailable: 75%
  selector:
    matchLabels:
      app.kubernetes.io/name: web
